// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Rms.Models;

public partial class ApplicantValidPhotoInfo
{
    [Key]
    public int SlNumber { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string BranchCode { get; set; }

    [StringLength(15)]
    [Unicode(false)]
    public string AGEXIDNO { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string ValidPhotoIDType { get; set; }

    [StringLength(200)]
    public string Description { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string FileName { get; set; }

    public byte[] ValidPhoto { get; set; }

    public DateOnly? IssueDate { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string IssuePlace { get; set; }

    public DateOnly? IDExpireDate { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string IssueAuthority { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Status { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string UserID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastUpdate { get; set; }

    [ForeignKey("BranchCode, AGEXIDNO")]
    [InverseProperty("ApplicantValidPhotoInfo")]
    public virtual ApplicantInfo ApplicantInfo { get; set; }

    [ForeignKey("BranchCode")]
    [InverseProperty("ApplicantValidPhotoInfo")]
    public virtual BranchInfo BranchCodeNavigation { get; set; }
}