// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Rms.Models;

[Index("BranchCode", "ApplicantAccNo", "SocialSecurityId", Name = "IX_ApplicantInfo")]
[Index("BranchCode", "Name", Name = "IX_ApplicantInfo_Name")]
[Index("BranchCode", "PhotoIDType", "PassportNo", Name = "IX_ApplicantInfo_Passport")]
[Index("BranchCode", "AGEXIDNO", Name = "IX_ApplicantInfo_Unique", IsUnique = true)]
[Index("BranchCode", "Mobile", Name = "IX_ApplicantInfo_mobile")]
[Index("AGEXIDNO", Name = "nci_wi_ApplicantInfo_3A006FD3287D13F3D025")]
public partial class ApplicantInfo
{
    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string BranchCode { get; set; }

    [Required]
    [StringLength(15)]
    [Unicode(false)]
    public string AGEXIDNO { get; set; }

    [Required]
    [StringLength(100)]
    public string FirstName { get; set; }

    [Required]
    [StringLength(50)]
    public string LastName { get; set; }

    [Required]
    [StringLength(150)]
    public string Name { get; set; }

    public DateOnly DOBDate { get; set; }

    [Required]
    [StringLength(200)]
    public string Address { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string ZipCode { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string Mobile { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string Telephone { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string PhotoIDType { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string PassportNo { get; set; }

    public DateOnly ExpiryDate { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string ApplicantAccNo { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string SocialSecurityId { get; set; }

    [StringLength(15)]
    [Unicode(false)]
    public string OtherIdExpiry { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string Nationality { get; set; }

    [StringLength(150)]
    public string FundingSource { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Occupation { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string OFACValidateReason { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Category { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Email { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string ApplicantNote { get; set; }

    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public string UserId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime LastUpdate { get; set; }

    [Key]
    public long SerialNo { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string PoliticalExposePerson { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string State { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Region { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string LGA { get; set; }

    [StringLength(10)]
    public string Gender { get; set; }

    [InverseProperty("ApplicantInfo")]
    public virtual ICollection<ApplicantValidPhotoInfo> ApplicantValidPhotoInfo { get; set; } = new List<ApplicantValidPhotoInfo>();

    [ForeignKey("BranchCode")]
    [InverseProperty("ApplicantInfo")]
    public virtual BranchInfo BranchCodeNavigation { get; set; }
}