// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Rms.Models;

[PrimaryKey("CountryCode", "BankCode", "RegistryKey")]
public partial class ApplicationRegistry
{
    [Key]
    [StringLength(10)]
    [Unicode(false)]
    public string CountryCode { get; set; }

    [Key]
    [StringLength(10)]
    [Unicode(false)]
    public string BankCode { get; set; }

    [Key]
    [StringLength(100)]
    [Unicode(false)]
    public string RegistryKey { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string RegistryValue { get; set; }

    [Required]
    [StringLength(5)]
    [Unicode(false)]
    public string Purpose { get; set; }

    [ForeignKey("BankCode")]
    [InverseProperty("ApplicationRegistry")]
    public virtual BranchInfo BankCodeNavigation { get; set; }
}