// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Rms.Models;

[PrimaryKey("BranchCode", "AGEXIDNO", "SerialNo")]
[Index("AGEXIDNO", Name = "nci_wi_Beneficiary_3A006FD3287D13F3D025")]
public partial class Beneficiary
{
    [Key]
    [StringLength(10)]
    [Unicode(false)]
    public string BranchCode { get; set; }

    [Key]
    [StringLength(15)]
    [Unicode(false)]
    public string AGEXIDNO { get; set; }

    [Key]
    public short SerialNo { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string FirstName { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string LastName { get; set; }

    [Required]
    [StringLength(150)]
    [Unicode(false)]
    public string Name { get; set; }

    public DateOnly? DOB { get; set; }

    [Required]
    [StringLength(200)]
    [Unicode(false)]
    public string Address { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Mobile { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string Email { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string DrawingBranchCode { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string AccountNo { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string PersonalId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string BeneficiaryCategory { get; set; }

    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public string UserId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime LastUpdate { get; set; }

    [StringLength(2)]
    [Unicode(false)]
    public string BeneficiaryType { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string OFACValidateReason { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string BenDistrict { get; set; }

    [ForeignKey("BranchCode")]
    [InverseProperty("BeneficiaryBranchCodeNavigation")]
    public virtual BranchInfo BranchCodeNavigation { get; set; }

    [ForeignKey("DrawingBranchCode")]
    [InverseProperty("BeneficiaryDrawingBranchCodeNavigation")]
    public virtual BranchInfo DrawingBranchCodeNavigation { get; set; }
}