// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Rms.Models;

[PrimaryKey("BranchCode", "RegistryKey")]
public partial class BranchRegistry
{
    [Key]
    [StringLength(10)]
    public string BranchCode { get; set; }

    [Key]
    [StringLength(50)]
    [Unicode(false)]
    public string RegistryKey { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string RegistryValue { get; set; }
}