// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Rms.Models;

[Index("BranchLevel", "SecondLevel", Name = "nci_wi_BranchInfo_1542F09DED7463DA920D")]
[Index("BranchLevel", "FirstLevel", "CountryCode", Name = "nci_wi_BranchInfo_78CFB1F6F0C6BC500E62")]
public partial class BranchInfo
{
    [Key]
    [StringLength(10)]
    [Unicode(false)]
    public string BranchCode { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string BranchName { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string ContactPerson { get; set; }

    [Required]
    [StringLength(120)]
    [Unicode(false)]
    public string Address { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Telephone { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Cellphone { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string Email { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string Fax { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string CountryCode { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string ZoneCode { get; set; }

    [Required]
    [StringLength(1)]
    [Unicode(false)]
    public string BranchLevel { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string FirstLevel { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string SecondLevel { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string ThirdLevel { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string FourthLevel { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string FifthLevel { get; set; }

    [Required]
    [StringLength(1)]
    [Unicode(false)]
    public string BranchType { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string NativeBranchCode { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string CurrencyCode { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string OwnBranchCode { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string AccountNoFC { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string AccountNoLC { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string UserId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastUpdate { get; set; }

    [InverseProperty("BranchCodeNavigation")]
    public virtual ICollection<ApplicantInfo> ApplicantInfo { get; set; } = new List<ApplicantInfo>();

    [InverseProperty("BranchCodeNavigation")]
    public virtual ICollection<ApplicantValidPhotoInfo> ApplicantValidPhotoInfo { get; set; } = new List<ApplicantValidPhotoInfo>();

    [InverseProperty("BankCodeNavigation")]
    public virtual ICollection<ApplicationRegistry> ApplicationRegistry { get; set; } = new List<ApplicationRegistry>();

    [InverseProperty("BranchCodeNavigation")]
    public virtual ICollection<Beneficiary> BeneficiaryBranchCodeNavigation { get; set; } = new List<Beneficiary>();

    [InverseProperty("DrawingBranchCodeNavigation")]
    public virtual ICollection<Beneficiary> BeneficiaryDrawingBranchCodeNavigation { get; set; } = new List<Beneficiary>();

    [InverseProperty("BranchCodeNavigation")]
    public virtual ICollection<ExchangeRateInfo> ExchangeRateInfo { get; set; } = new List<ExchangeRateInfo>();

    [InverseProperty("BranchCodeNavigation")]
    public virtual ICollection<FeesInfo> FeesInfo { get; set; } = new List<FeesInfo>();

    [InverseProperty("IssuingBranchNavigation")]
    public virtual ICollection<Remittance> RemittanceIssuingBranchNavigation { get; set; } = new List<Remittance>();

    [InverseProperty("RespondingBranchNavigation")]
    public virtual ICollection<Remittance> RemittanceRespondingBranchNavigation { get; set; } = new List<Remittance>();
}