// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Rms.Models;

[PrimaryKey("BankCode", "Code")]
[Index("BankCode", "Type", Name = "IX_CommonCode_Type")]
public partial class CommonCode
{
    [Key]
    [StringLength(10)]
    [Unicode(false)]
    public string BankCode { get; set; }

    [Key]
    [StringLength(10)]
    [Unicode(false)]
    public string Code { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string Type { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string TypeValue { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string DisplayCode { get; set; }

    public bool Status { get; set; }
}