// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Rms.Models;

[PrimaryKey("BranchCode", "TransDate", "CurrencyCode", "SLNO", "ExchangeRateType")]
public partial class ExchangeRateInfo
{
    [Key]
    [StringLength(10)]
    [Unicode(false)]
    public string BranchCode { get; set; }

    [Key]
    public DateOnly TransDate { get; set; }

    [Key]
    [StringLength(10)]
    [Unicode(false)]
    public string CurrencyCode { get; set; }

    [Key]
    public byte SLNO { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal AmountFrom { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal AmountTo { get; set; }

    [Column(TypeName = "decimal(12, 4)")]
    public decimal ExchangeRate { get; set; }

    [Column(TypeName = "decimal(12, 4)")]
    public decimal SellingRate { get; set; }

    [Column(TypeName = "decimal(12, 4)")]
    public decimal BuyingRate { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string BaseCurrencyCode { get; set; }

    [Key]
    [StringLength(10)]
    [Unicode(false)]
    public string ExchangeRateType { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string UserId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastUpdate { get; set; }

    [ForeignKey("BranchCode")]
    [InverseProperty("ExchangeRateInfo")]
    public virtual BranchInfo BranchCodeNavigation { get; set; }
}