// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Rms.Models;

[PrimaryKey("BranchCode", "AccountType", "TransType", "SLNO")]
public partial class FeesInfo
{
    [Key]
    [StringLength(10)]
    [Unicode(false)]
    public string BranchCode { get; set; }

    [Key]
    [StringLength(10)]
    [Unicode(false)]
    public string AccountType { get; set; }

    [Key]
    [StringLength(10)]
    [Unicode(false)]
    public string TransType { get; set; }

    [Key]
    public byte SLNO { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string TransMode { get; set; }

    [Column(TypeName = "decimal(18, 0)")]
    public decimal AmountFrom { get; set; }

    [Column(TypeName = "decimal(18, 0)")]
    public decimal AmountTo { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal Fees { get; set; }

    [Column(TypeName = "decimal(7, 2)")]
    public decimal FeesPercent { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal MinFee { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal MaxFee { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string GLCode { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string UserId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastUpdate { get; set; }

    [ForeignKey("BranchCode")]
    [InverseProperty("FeesInfo")]
    public virtual BranchInfo BranchCodeNavigation { get; set; }
}